# SAM Template for automata-ws function
# This file will be merged into the root template.yaml during local testing
# Note: Run 'bun run build:functions' before 'bun run sam:local'

# ============================================================
# WebSocket API Gateway
# ============================================================

AutomataWebSocketApi:
  Type: AWS::ApiGatewayV2::Api
  Properties:
    Name: !Sub 'automabase-ws-${Environment}'
    ProtocolType: WEBSOCKET
    RouteSelectionExpression: '$request.body.action'

AutomataWebSocketStage:
  Type: AWS::ApiGatewayV2::Stage
  Properties:
    ApiId: !Ref AutomataWebSocketApi
    StageName: !Ref Environment
    AutoDeploy: true

# ============================================================
# WebSocket Lambda Function
# ============================================================

AutomataWsFunction:
  Type: AWS::Serverless::Function
  Properties:
    # Points directly to the pre-built dist directory (built by esbuild)
    CodeUri: functions/automata-ws/dist
    Handler: index.handler
    Runtime: nodejs24.x
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AUTOMABASE_TABLE: !Sub 'automabase-${Environment}'
        REQUEST_ID_TABLE: !Ref RequestIdTable
        WEBSOCKET_API_ENDPOINT: !Sub 'https://${AutomataWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
        # Local dev variables - empty in production, overridden by env.json in local
        LOCAL_JWT_PUBLIC_KEY: ''
        LOCAL_JWT_ISSUER: ''
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref AutomabaseTable
      - DynamoDBCrudPolicy:
          TableName: !Ref RequestIdTable
      # 允许向 WebSocket 连接发送消息
      - Statement:
          - Effect: Allow
            Action:
              - 'execute-api:ManageConnections'
            Resource:
              - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*'

# WebSocket 路由权限
AutomataWsFunctionConnectPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref AutomataWsFunction
    Action: 'lambda:InvokeFunction'
    Principal: apigateway.amazonaws.com
    SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*/$connect'

AutomataWsFunctionDisconnectPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref AutomataWsFunction
    Action: 'lambda:InvokeFunction'
    Principal: apigateway.amazonaws.com
    SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*/$disconnect'

AutomataWsFunctionDefaultPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref AutomataWsFunction
    Action: 'lambda:InvokeFunction'
    Principal: apigateway.amazonaws.com
    SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*/$default'

# ============================================================
# WebSocket 路由
# ============================================================

ConnectRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref AutomataWebSocketApi
    RouteKey: '$connect'
    AuthorizationType: NONE
    Target: !Sub 'integrations/${ConnectIntegration}'

ConnectIntegration:
  Type: AWS::ApiGatewayV2::Integration
  Properties:
    ApiId: !Ref AutomataWebSocketApi
    IntegrationType: AWS_PROXY
    IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AutomataWsFunction.Arn}/invocations'

DisconnectRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref AutomataWebSocketApi
    RouteKey: '$disconnect'
    AuthorizationType: NONE
    Target: !Sub 'integrations/${DisconnectIntegration}'

DisconnectIntegration:
  Type: AWS::ApiGatewayV2::Integration
  Properties:
    ApiId: !Ref AutomataWebSocketApi
    IntegrationType: AWS_PROXY
    IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AutomataWsFunction.Arn}/invocations'

DefaultRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref AutomataWebSocketApi
    RouteKey: '$default'
    AuthorizationType: NONE
    Target: !Sub 'integrations/${DefaultIntegration}'

DefaultIntegration:
  Type: AWS::ApiGatewayV2::Integration
  Properties:
    ApiId: !Ref AutomataWebSocketApi
    IntegrationType: AWS_PROXY
    IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AutomataWsFunction.Arn}/invocations'

