# SAM Template for automata-ws function
# This file will be merged into the root template.yaml during local testing
# Note: Run 'bun run build:functions' before 'bun run sam:local'

AutomataWsFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: functions/automata-ws/dist
    Handler: index.handler
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AUTOMABASE_TABLE: !Ref AutomabaseTable
        CONNECTIONS_TABLE: !Ref ConnectionsTable
        WEBSOCKET_ENDPOINT: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref AutomabaseTable
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnectionsTable
      - Statement:
          - Effect: Allow
            Action:
              - execute-api:ManageConnections
            Resource:
              - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*"
