# SAM Template for tenant-api function
# This file will be merged into the root template.yaml during local testing
# Note: Run 'bun run build:functions' before 'bun run sam:local'

TenantApiFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: functions/tenant-api/dist
    Handler: index.handler
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AUTOMABASE_TABLE: !Ref AutomabaseTable
        REQUEST_ID_TABLE: !Ref RequestIdTable
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref AutomabaseTable
      - DynamoDBCrudPolicy:
          TableName: !Ref RequestIdTable
    Events:
      GetTenant:
        Type: Api
        Properties:
          Path: /tenant
          Method: GET
      UpdateTenant:
        Type: Api
        Properties:
          Path: /tenant
          Method: PATCH
