AWSTemplateFormatVersion: '2010-09-31'
Transform: AWS::Serverless-2016-10-31
Description: Automabase Lambda Functions

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        # Lambda function references for cross-function invocation
        JSONATA_EVAL_FUNCTION: !Ref JsonataEvalFunction

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  # Function resources will be merged from functions/*/template.yaml
  # Run 'bun run sam:merge' to generate the merged template
  
  # Placeholder resource to prevent empty Resources section error
  # This will be overwritten when merging templates
  Placeholder:
    Type: AWS::CloudFormation::WaitConditionHandle

# Outputs:
#   ApiGatewayApi:
#     Description: API Gateway endpoint URL
#     Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
