AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Automabase Lambda Functions

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  # ============================================================
  # Cognito User Pool
  # ============================================================
  
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !Sub 'automabase-users-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserPoolTags:
        Environment: !Ref Environment
        ManagedBy: CloudFormation
  
  # 基础 Client (仅 Cognito 原生认证)
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub 'automabase-client-${Environment}'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      # 只使用 Cognito 原生认证，外部 IdP 需要单独配置
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - 'http://localhost:3201/callback'
        # 生产环境: 添加你的域名，如 'https://your-domain.com/callback'
      LogoutURLs:
        - 'http://localhost:3201/logout'
        # 生产环境: 添加你的域名，如 'https://your-domain.com/logout'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      PreventUserExistenceErrors: ENABLED
  
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub 'automabase-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool
  
  # ============================================================
  # External Identity Providers (可选，需手动配置)
  # ============================================================
  # 要启用 Google/GitHub 登录，请:
  # 1. 在 Google Cloud Console / GitHub Settings 创建 OAuth App
  # 2. 取消下面的注释并填入 client_id/client_secret
  # 3. 在 UserPoolClient 的 SupportedIdentityProviders 中添加 'Google' 或 'GitHub'
  
  # GoogleIdentityProvider:
  #   Type: AWS::Cognito::UserPoolIdentityProvider
  #   Properties:
  #     UserPoolId: !Ref UserPool
  #     ProviderName: Google
  #     ProviderType: Google
  #     ProviderDetails:
  #       client_id: !Ref GoogleClientId
  #       client_secret: !Ref GoogleClientSecret
  #       authorize_scopes: 'email profile openid'
  #     AttributeMapping:
  #       email: email
  #       name: name
  #       picture: picture
  #       username: sub
  
  # GitHubIdentityProvider:
  #   Type: AWS::Cognito::UserPoolIdentityProvider
  #   Properties:
  #     UserPoolId: !Ref UserPool
  #     ProviderName: SignInWithApple  # GitHub 需要使用 OIDC 配置
  #     ProviderType: OIDC
  #     ProviderDetails:
  #       client_id: !Ref GitHubClientId
  #       client_secret: !Ref GitHubClientSecret
  #       authorize_scopes: 'openid user:email'
  #       oidc_issuer: 'https://github.com'
  #     AttributeMapping:
  #       email: email
  #       name: name
  #       username: sub
  
  # ============================================================
  # DynamoDB Tables
  # ============================================================
  AutomabaseTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'automabase-${Environment}'
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
        - AttributeName: gsi2pk
          AttributeType: S
        - AttributeName: gsi2sk
          AttributeType: S
        - AttributeName: lsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        # GSI1: OAuth lookup, Account's Automatas, App's Blueprints
        - IndexName: gsi1-multipurpose-index
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI2: App's Automatas (for stats and auditing)
        - IndexName: gsi2-app-automata-index
          KeySchema:
            - AttributeName: gsi2pk
              KeyType: HASH
            - AttributeName: gsi2sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      LocalSecondaryIndexes:
        - IndexName: lsi1-event-type-index
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true

  RequestIdTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub 'automabase-request-ids-${Environment}'
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true

  # ============================================================
  # Lambda Functions (from stacks/automabase)
  # ============================================================
  
  # HTTP API Lambda Function
  AutomataApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Points directly to the pre-built dist directory (built by esbuild)
      CodeUri: stacks/automabase/dist/automata-api
      Handler: index.handler
      Runtime: nodejs24.x
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          AUTOMABASE_TABLE: !Sub 'automabase-${Environment}'
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_CLIENT_ID: !Ref UserPoolClient
          # WebSocket API endpoint for broadcasting state updates
          WEBSOCKET_API_ENDPOINT: !Sub 'https://${AutomataWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
          # Local dev variables - empty in production, overridden by env.json in local
          LOCAL_JWT_PUBLIC_KEY: ''
          LOCAL_JWT_ISSUER: ''
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AutomabaseTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RequestIdTable
        # 允许向 WebSocket 连接发送消息（用于广播状态更新）
        - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*'
      Events:
        # Account API
        AccountsMe:
          Type: Api
          Properties:
            Path: /v1/accounts/me
            Method: ANY
        Accounts:
          Type: Api
          Properties:
            Path: /v1/accounts
            Method: ANY
        AccountById:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}
            Method: ANY

        # Device API - nested under /accounts/me
        AccountMeDevices:
          Type: Api
          Properties:
            Path: /v1/accounts/me/devices
            Method: ANY
        AccountMeDeviceById:
          Type: Api
          Properties:
            Path: /v1/accounts/me/devices/{deviceId}
            Method: ANY

        # Automata API - nested under /accounts/{accountId}
        AccountAutomatas:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/automatas
            Method: ANY
        AccountAutomataById:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/automatas/{automataId}
            Method: ANY
        AccountAutomataState:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/automatas/{automataId}/state
            Method: ANY
        AccountAutomataArchive:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/automatas/{automataId}/archive
            Method: ANY
        AccountAutomataUnarchive:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/automatas/{automataId}/unarchive
            Method: ANY

        # Event API - nested under /accounts/{accountId}/automatas/{automataId}
        AccountAutomataEvents:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/automatas/{automataId}/events
            Method: ANY
        AccountAutomataEventById:
          Type: Api
          Properties:
            Path: /v1/accounts/{accountId}/automatas/{automataId}/events/{baseVersion}
            Method: ANY

        # WebSocket Token API
        WsToken:
          Type: Api
          Properties:
            Path: /v1/ws/token
            Method: POST

  # ============================================================
  # WebSocket API Gateway
  # ============================================================

  AutomataWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub 'automabase-ws-${Environment}'
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.action'

  AutomataWebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref AutomataWebSocketApi
      StageName: !Ref Environment
      AutoDeploy: true

  # ============================================================
  # WebSocket Lambda Function
  # ============================================================

  AutomataWsFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Points directly to the pre-built dist directory (built by esbuild)
      CodeUri: stacks/automabase/dist/automata-ws
      Handler: index.handler
      Runtime: nodejs24.x
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          AUTOMABASE_TABLE: !Sub 'automabase-${Environment}'
          REQUEST_ID_TABLE: !Ref RequestIdTable
          WEBSOCKET_API_ENDPOINT: !Sub 'https://${AutomataWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
          # Local dev variables - empty in production, overridden by env.json in local
          LOCAL_JWT_PUBLIC_KEY: ''
          LOCAL_JWT_ISSUER: ''
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AutomabaseTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RequestIdTable
        # 允许向 WebSocket 连接发送消息
        - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*'

  # WebSocket 路由权限
  AutomataWsFunctionConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutomataWsFunction
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*/$connect'

  AutomataWsFunctionDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutomataWsFunction
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*/$disconnect'

  AutomataWsFunctionDefaultPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutomataWsFunction
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*/$default'

  # ============================================================
  # WebSocket 路由
  # ============================================================

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AutomataWebSocketApi
      RouteKey: '$connect'
      AuthorizationType: NONE
      Target: !Sub 'integrations/${ConnectIntegration}'

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AutomataWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AutomataWsFunction.Arn}/invocations'

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AutomataWebSocketApi
      RouteKey: '$disconnect'
      AuthorizationType: NONE
      Target: !Sub 'integrations/${DisconnectIntegration}'

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AutomataWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AutomataWsFunction.Arn}/invocations'

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AutomataWebSocketApi
      RouteKey: '$default'
      AuthorizationType: NONE
      Target: !Sub 'integrations/${DefaultIntegration}'

  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AutomataWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AutomataWsFunction.Arn}/invocations'

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
  
  UserPoolDomainUrl:
    Description: Cognito Hosted UI URL
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolDomainUrl'
  
  AutomabaseTableName:
    Description: DynamoDB Table Name
    Value: !Ref AutomabaseTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'
  
  RequestIdTableName:
    Description: Request ID Table Name
    Value: !Ref RequestIdTable
    Export:
      Name: !Sub '${AWS::StackName}-RequestIdTableName'
  
  WebSocketApiEndpoint:
    Description: WebSocket API Endpoint
    Value: !Sub 'wss://${AutomataWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-WebSocketApiEndpoint'

  HttpApiEndpoint:
    Description: HTTP API Endpoint
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: !Sub '${AWS::StackName}-HttpApiEndpoint'
