# SAM Template for tenant-admin-api function
# This file will be merged into the root template.yaml during local testing
# Note: Run 'bun run build:functions' before 'bun run sam:local'

TenantAdminApiFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub 'automabase-tenant-admin-api-${Environment}'
    CodeUri: functions/tenant-admin-api/dist
    Handler: index.handler
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 512
    Description: Tenant administration API for platform management
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        TABLE_NAME: !Ref AutomabaseTable
        ADMIN_API_KEY_SECRET: automabase/admin-api-key
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref AutomabaseTable
      - Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:automabase/admin-api-key*'
    Events:
      CreateTenant:
        Type: Api
        Properties:
          Path: /admin/tenants
          Method: POST
      ListTenants:
        Type: Api
        Properties:
          Path: /admin/tenants
          Method: GET
      GetTenant:
        Type: Api
        Properties:
          Path: /admin/tenants/{tenantId}
          Method: GET
      UpdateTenant:
        Type: Api
        Properties:
          Path: /admin/tenants/{tenantId}
          Method: PATCH
      SuspendTenant:
        Type: Api
        Properties:
          Path: /admin/tenants/{tenantId}/suspend
          Method: POST
      ResumeTenant:
        Type: Api
        Properties:
          Path: /admin/tenants/{tenantId}/resume
          Method: POST
      DeleteTenant:
        Type: Api
        Properties:
          Path: /admin/tenants/{tenantId}
          Method: DELETE
