# SAM Template for automata-api function
# This file will be merged into the root template.yaml during local testing
# Note: Run 'bun run build:functions' before 'bun run sam:local'

AutomataApiFunction:
  Type: AWS::Serverless::Function
  Properties:
    # Points directly to the pre-built dist directory (built by esbuild)
    CodeUri: functions/automata-api/dist
    Handler: index.handler
    Runtime: nodejs24.x
    Environment:
      Variables:
        NODE_ENV: ${Env:NODE_ENV,prod}
        LOCAL_DEV_MODE: ${Env:LOCAL_DEV_MODE,false}
        DYNAMODB_TABLE_NAME: ${Env:DYNAMODB_TABLE_NAME,automabase-dev}
        COGNITO_USER_POOL_ID: ${Env:COGNITO_USER_POOL_ID,}
        COGNITO_CLIENT_ID: ${Env:COGNITO_CLIENT_ID,}
    Events:
      AccountsMe:
        Type: Api
        Properties:
          Path: /v1/accounts/me
          Method: ANY
      Accounts:
        Type: Api
        Properties:
          Path: /v1/accounts
          Method: ANY
      AccountById:
        Type: Api
        Properties:
          Path: /v1/accounts/{accountId}
          Method: ANY
