# SAM Template for automata-api function
# This file will be merged into the root template.yaml during deployment
# Note: Run 'bun run build:functions' before 'bun run sam:build'

AutomataApiFunction:
  Type: AWS::Serverless::Function
  Properties:
    # Points directly to the pre-built dist directory (built by esbuild)
    CodeUri: functions/automata-api/dist
    Handler: index.handler
    Runtime: nodejs24.x
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        LOCAL_DEV_MODE: 'false'
        DYNAMODB_TABLE_NAME: !Ref AutomabaseTable
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref AutomabaseTable
      - DynamoDBCrudPolicy:
          TableName: !Ref RequestIdTable
    Events:
      AccountsMe:
        Type: Api
        Properties:
          Path: /v1/accounts/me
          Method: ANY
      Accounts:
        Type: Api
        Properties:
          Path: /v1/accounts
          Method: ANY
      AccountById:
        Type: Api
        Properties:
          Path: /v1/accounts/{accountId}
          Method: ANY
