# SAM Template for automata-api function
# This file will be merged into the root template.yaml during deployment
# Note: Run 'bun run build:functions' before 'bun run sam:build'

AutomataApiFunction:
  Type: AWS::Serverless::Function
  Properties:
    # Points directly to the pre-built dist directory (built by esbuild)
    CodeUri: functions/automata-api/dist
    Handler: index.handler
    Runtime: nodejs24.x
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        DYNAMODB_TABLE_NAME: !Ref AutomabaseTable
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
        # WebSocket API endpoint for broadcasting state updates
        WEBSOCKET_API_ENDPOINT: !Sub 'https://${AutomataWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
        # Local dev variables - empty in production, overridden by env.json in local
        LOCAL_JWT_PUBLIC_KEY: ''
        LOCAL_JWT_ISSUER: ''
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref AutomabaseTable
      - DynamoDBCrudPolicy:
          TableName: !Ref RequestIdTable
      # 允许向 WebSocket 连接发送消息（用于广播状态更新）
      - Statement:
          - Effect: Allow
            Action:
              - 'execute-api:ManageConnections'
            Resource:
              - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AutomataWebSocketApi}/*'
    Events:
      # Account API
      AccountsMe:
        Type: Api
        Properties:
          Path: /v1/accounts/me
          Method: ANY
      Accounts:
        Type: Api
        Properties:
          Path: /v1/accounts
          Method: ANY
      AccountById:
        Type: Api
        Properties:
          Path: /v1/accounts/{accountId}
          Method: ANY

      # Automata API - nested under /accounts/{accountId}
      AccountAutomatas:
        Type: Api
        Properties:
          Path: /v1/accounts/{accountId}/automatas
          Method: ANY
      AccountAutomataById:
        Type: Api
        Properties:
          Path: /v1/accounts/{accountId}/automatas/{automataId}
          Method: ANY
      AccountAutomataState:
        Type: Api
        Properties:
          Path: /v1/accounts/{accountId}/automatas/{automataId}/state
          Method: ANY

      # Event API - nested under /accounts/{accountId}/automatas/{automataId}
      AccountAutomataEvents:
        Type: Api
        Properties:
          Path: /v1/accounts/{accountId}/automatas/{automataId}/events
          Method: ANY
      AccountAutomataEventById:
        Type: Api
        Properties:
          Path: /v1/accounts/{accountId}/automatas/{automataId}/events/{baseVersion}
          Method: ANY

      # WebSocket Token API
      WsToken:
        Type: Api
        Properties:
          Path: /v1/ws/token
          Method: POST
