# SAM Template for event-stream function
# This file will be merged into the root template.yaml during local testing
# Note: Run 'bun run build:functions' before 'bun run sam:local'

EventStreamFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: functions/event-stream/dist
    Handler: index.handler
    Runtime: nodejs24.x
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: ${Env:NODE_ENV,prod}
        EVENT_STREAM_TABLE: !Ref EventStreamTable
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref EventStreamTable
    Events:
      # Stream operations
      CreateStream:
        Type: Api
        Properties:
          Path: /streams
          Method: POST
      DeleteStream:
        Type: Api
        Properties:
          Path: /streams/{streamId}
          Method: DELETE
      # Event operations
      PushEvent:
        Type: Api
        Properties:
          Path: /streams/{streamId}/events
          Method: POST
      GetEvent:
        Type: Api
        Properties:
          Path: /streams/{streamId}/events/{eventId}
          Method: GET
      # Query operations
      Backtrace:
        Type: Api
        Properties:
          Path: /streams/{streamId}/backtrace
          Method: GET
      Replay:
        Type: Api
        Properties:
          Path: /streams/{streamId}/replay
          Method: GET

EventStreamTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: !Sub ${AWS::StackName}-event-stream
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
